### ISSUE TITLE
Build graphql-typescript-definitions SK1 plugin

### ISSUE THREAD

**Issue by ismail-syed** [Shopify/loom#112]
In SK0, before running webpack dev mode, we built [an apps graphql typescript definitions](https://github.com/Shopify/sewing-kit/blob/ebe11ae83281b13a1fea6341a3572cbdb7bb0ab7/packages/sewing-kit/src/tools/webpack/dev/index.ts#L114-L115). With spinx, it’s recommended that you run [`yarn refresh-graphql`](https://github.com/Shopify/web/blob/master/spinx/README.md#usage) to update your graphql TS definitions. 

IIRC, we don’t have this capability yet in an SK1 world, so we’ll need to build it in. 
This is medium-priority because if we don’t deliver this for our [current project](https://vault.shopify.io/projects/17188), we can fallback to SK0 in the interim. 

The SK1 plugin for graphql-typescript-definition support will also have to be packaged in https://github.com/Shopify/sewing-kit-next-plugins/blob/main/packages/plugin-quilt/src/index.ts#L54 for apps to easily consume.

**Comment by BPScott** [comment]
[Included in plugin-build-library](https://github.com/Shopify/loom/blob/2a5409983db8f4226534d394780bf8a1ab2522cb/packages/loom-plugin-build-library/src/plugin-generate-graphql-types.ts)
